version: '3.8'
services:
  postgres:
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # Bind to 5433 to avoid colliding with the main PostgreSQL instance on the host machine
      - '5433:5432'
volumes:
  postgres:
