export const typeToName = {
  archaeological: 'Archaeological',
  arts_centre: 'Arts Centre',
  artwork: 'Artwork',
  atm: 'Atm',
  attraction: 'Attraction',
  bakery: 'Bakery',
  bank: 'Bank',
  bar: 'Bar',
  battlefield: 'Battlefield',
  beauty_shop: 'Beauty Shop',
  bench: 'Bench',
  beverages: 'Beverages',
  bicycle_rental: 'Bicycle Rental',
  bicycle_shop: 'Bicycle Shop',
  biergarten: 'Biergarten',
  bookshop: 'Bookshop',
  butcher: 'Butcher',
  cafe: 'Cafe',
  camera_surveillance: 'Camera Surveillance',
  camp_site: 'Camp Site',
  caravan_site: 'Caravan Site',
  car_dealership: 'Car Dealership',
  car_rental: 'Car Rental',
  car_sharing: 'Car Sharing',
  car_wash: 'Car Wash',
  chalet: 'Chalet',
  chemist: 'Chemist',
  cinema: 'Cinema',
  clothes: 'Clothes',
  college: 'College',
  comms_tower: 'Comms Tower',
  community_centre: 'Community Centre',
  computer_shop: 'Computer Shop',
  convenience: 'Convenience',
  courthouse: 'Courthouse',
  dentist: 'Dentist',
  department_store: 'Department Store',
  doctors: 'Doctors',
  dog_park: 'Dog Park',
  doityourself: 'Doityourself',
  drinking_water: 'Drinking Water',
  embassy: 'Embassy',
  fast_food: 'Fast Food',
  fire_station: 'Fire Station',
  florist: 'Florist',
  food_court: 'Food Court',
  fountain: 'Fountain',
  furniture_shop: 'Furniture Shop',
  garden_centre: 'Garden Centre',
  gift_shop: 'Gift Shop',
  golf_course: 'Golf Course',
  graveyard: 'Graveyard',
  greengrocer: 'Greengrocer',
  guesthouse: 'Guesthouse',
  hairdresser: 'Hairdresser',
  hospital: 'Hospital',
  hostel: 'Hostel',
  hotel: 'Hotel',
  hunting_stand: 'Hunting Stand',
  jeweller: 'Jeweller',
  kindergarten: 'Kindergarten',
  kiosk: 'Kiosk',
  laundry: 'Laundry',
  library: 'Library',
  mall: 'Mall',
  memorial: 'Memorial',
  mobile_phone_shop: 'Mobile Phone Shop',
  monument: 'Monument',
  motel: 'Motel',
  museum: 'Museum',
  newsagent: 'Newsagent',
  nightclub: 'Nightclub',
  nursing_home: 'Nursing Home',
  observation_tower: 'Observation Tower',
  optician: 'Optician',
  outdoor_shop: 'Outdoor Shop',
  park: 'Park',
  pharmacy: 'Pharmacy',
  picnic_site: 'Picnic Site',
  pitch: 'Pitch',
  playground: 'Playground',
  police: 'Police',
  post_box: 'Post Box',
  post_office: 'Post Office',
  prison: 'Prison',
  pub: 'Pub',
  recycling: 'Recycling',
  recycling_clothes: 'Recycling Clothes',
  recycling_glass: 'Recycling Glass',
  recycling_metal: 'Recycling Metal',
  recycling_paper: 'Recycling Paper',
  restaurant: 'Restaurant',
  ruins: 'Ruins',
  school: 'School',
  shelter: 'Shelter',
  shoe_shop: 'Shoe Shop',
  sports_centre: 'Sports Centre',
  sports_shop: 'Sports Shop',
  stadium: 'Stadium',
  stationery: 'Stationery',
  supermarket: 'Supermarket',
  swimming_pool: 'Swimming Pool',
  telephone: 'Telephone',
  theatre: 'Theatre',
  theme_park: 'Theme Park',
  toilet: 'Toilet',
  tourist_info: 'Tourist Info',
  tower: 'Tower',
  town_hall: 'Town Hall',
  toy_shop: 'Toy Shop',
  track: 'Track',
  travel_agent: 'Travel Agent',
  university: 'University',
  vending_any: 'Vending Any',
  vending_cigarette: 'Vending Cigarette',
  vending_machine: 'Vending Machine',
  vending_parking: 'Vending Parking',
  veterinary: 'Veterinary',
  video_shop: 'Video Shop',
  viewpoint: 'Viewpoint',
  waste_basket: 'Waste Basket',
  water_mill: 'Water Mill',
  water_tower: 'Water Tower',
  water_well: 'Water Well',
  water_works: 'Water Works',
  wayside_cross: 'Wayside Cross',
  wayside_shrine: 'Wayside Shrine',
  zoo: 'Zoo',
}
